server:
  address: localhost
  port: 8088
spring:
  redis:
    host: 127.0.0.1
    port: 6379

  application:
    name: StockDividend

  jpa:
    hibernate:
      ddl-auto: create
      use-new-id-generator-mappings: false
    show-sql: true
    defer-datasource-initialization: true

  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:tcp://localhost/~/test
    username: sa
    password:

  jwt:
    secret: c3ByaW5nLWJvb3QtU3RvY2tEaXZpZGVuZA==

  h2:
    console:
      enabled: true
      path: /h2-console


scheduler:
  scrap:
    yahoo: "0 0 0 * * *"
